language: bash

sudo: required

services:
  - docker

before_script:
    - chmod +x ./bashbrew/travis.sh
    - chmod +x ./bashbrew/bashbrew.sh
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"


# --no-build because we has no Docker in Travis :)
script:
    - ./bashbrew/travis.sh
