language: bash

sudo: required

services:
  - docker

before_script:
    - env | sort
    - chmod +x ./bashbrew/travis.sh
    - chmod +x ./bashbrew/bashbrew.sh

# --no-build because we has no Docker in Travis :)
script:
    - ./bashbrew/travis.sh
