language: bash

# allow for use of Docker-based workers
sudo: false

before_script:
    - env | sort
    - chmod +x ./bashbrew/travis.sh
    - chmod +x ./bashbrew/bashbrew.sh

# --no-build because we has no Docker in Travis :)
script:
    - ./bashbrew/travis.sh
